### ISSUE TITLE
Add multi theme support (Light and Dark)

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot-mobile-app#103]
Refer [UI kitten runtime-theming](https://akveo.github.io/react-native-ui-kitten/docs/guides/runtime-theming#runtime-theming)

**Comment by dibakar95** [comment]
Can I take this issue? @muhsin-k

**Comment by muhsin-k** [comment]
@dibakar95 Sure. Let us know if you need any help :)

**Comment by mayank-budhiraja** [comment]
@muhsin-k can I take this issue?

**Comment by muhsin-k** [comment]
@mayank-budhiraja Please feel free to go ahead

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/1042

**Comment by mayank-budhiraja** [comment]
@muhsin-k I have started working on this and I am going to use the develop branch

**Comment by muhsin-k** [comment]
@mayank-budhiraja Sure. Please feel free to go ahead. Feel free to reach out if you have any other questions

**Comment by mayank-budhiraja** [comment]
@muhsin-k Over here, do I need to self-host the backend to contribute to mobile app as well ?

**Comment by muhsin-k** [comment]
@mayank-budhiraja  You could able to create a new account at https://app.chatwoot.com/ and use the same for the mobile app.

**Comment by mayank-budhiraja** [comment]
@muhsin-k I will also have to set the .env variable for the app to function properly. Can you please elaborate on that part? As it's not clear in the docs.

**Comment by muhsin-k** [comment]
@mayank-budhiraja The only required variable is sentry DSN. You can comment this https://github.com/chatwoot/chatwoot-mobile-app/blob/develop/index.js#L10 for disabling sentry

**Comment by mayank-budhiraja** [comment]
@muhsin-k thanks for the help. I have successfully setup the app. I am working on the same. I will keep you update here. :)

**Comment by mayank-budhiraja** [comment]
@muhsin-k need an assistance I tried implementing as per the docs but it doesn't seems to working. Can you please more guidance on this?
Thanks

**Comment by gokul1099** [comment]
Can I take this issue? @muhsin-k

**Comment by gokul1099** [comment]
Is this feature completed?? shall I work on this

**Comment by mahede182** [comment]
Is this issue still open?

**Comment by putuwahyu29** [comment]
Dark mode theme ?

**Comment by muhsin-k** [comment]
We have started working on an improved version of the mobile app with dark theme.
