### ISSUE TITLE
Picture message shown as null in conversation list

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#160]
If the last message is a picture message, it is displayed as null.

**Comment by muhsin-k** [comment]
It is happening in dashboard too. 
<img width="1204" alt="Screenshot 2020-06-04 at 4 31 25 PM" src="https://user-images.githubusercontent.com/12408980/83749135-da7ef700-a680-11ea-9c80-c4be2780a10f.png">

**Comment by muhsin-k** [comment]
@pranavrajs Is this issue fixed?
