### ISSUE TITLE
Feature: Allow line breaks when replying to messages

### ISSUE THREAD

**Issue by ericalli** [chatwoot/chatwoot-mobile-app#244]
Currently when replying to messages, it's a single line input field. Would it be possible to allow for line breaks or at the very least convert to a multi-line input for better readability?

**Comment by iamprayush** [comment]
Hey @muhsin-k! Are you currently working on this? If not, can I take this up?

**Comment by muhsin-k** [comment]
@iamprayush No. Please feel free to go ahead
