### ISSUE TITLE
How to setup Push notifications

### ISSUE THREAD

**Issue by Sx3** [chatwoot/chatwoot-mobile-app#247]
Is there any guides to setup push notification for mobile clients ?

**Comment by sojan-official** [comment]
@Sx3  we don't have documentation for this at the moment. But its something that we are working on.  

if you want to build mobile apps for your own. you will have to build the apps with your own firebase keys.  
follow the guidelines in https://rnfirebase.io/#installation  to include the keys while building the react native apps. 

you will also have to use the same key in your chatwoot server as well. 
https://github.com/chatwoot/chatwoot/blob/29bd05ccfb73ce97b2647f11c24a50c02ef27364/.env.example#L115 
change environment variables referred here. 


the process might be slightly overwhelming if you could share the steps where you are stuck, probably the team could guide you through and we can try to capture the final results into the documentation. 

cc: @muhsin-k

**Comment by surbhitrao** [comment]
Hi please find the steps for setting up push notifications on android 
https://www.notion.so/Setting-up-Push-Notifications-on-Android-3f88f72b1d0e4653aea2ce0e1417ac95

**Comment by sojan-official** [comment]
Thanks a lot for documenting this @surbhitrao

@muhsin-k  could you take a look and see if we can bring this into our official documentation?

**Comment by muhsin-k** [comment]
@surbhitrao Thanks for the doc.

@sojan-official I will add this to the self-hosted installation guide.

**Comment by muhsin-k** [comment]
Finally, we have added support for push notifications in our community edition of Chatwoot. You would now be able to use the Official mobile app with push notifications without any additional configuration. More details can be found [here](https://github.com/chatwoot/chatwoot/releases/tag/v1.19.0)
