### ISSUE TITLE
"Invalid installation url" when trying to change URL to Linux hosted app

### ISSUE THREAD

**Issue by pwrsurge** [chatwoot/chatwoot-mobile-app#252]
For some reason, I keep getting "Invalid installation url" error when I try to change URL to a self hosted Linux chatwoot app that was setup on a new Ubunutu 20.04 system using the installation script at https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_20.04.sh.

The installation has no issues as I am able to login to the web interface just fine using the default john@acme.inc account.  Tried the app on two separate Android devices and both have the same error message when trying to change the URL.

The default app.chatwoot.com URL works fine but would like to use the app on our self hosted install.

Any ideas how to debug? The error message should have more details added in a future app versoin to let us know exactly why the installation url is invalid.

**Comment by muhsin-k** [comment]
@pwrsurge Did you add the SSL certificate to chatwoot app? The mobile app supports secure chatwoot installation only. To add an SSL certificate, please follow the [guide](https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm)

**Comment by vfasoulas** [comment]
same issue for me, and the site (https://chatwoot.hmu.gr) has SSL certificate

**Comment by pranavrajs** [comment]
@muhsin-k I believe the problem here is that the app does not show any indication that full URL with `https` should be not be added. In the case @vfasoulas mentioned, I was able to move past the installation URL screen by inputting `chatwoot.hm.gr` instead of `https://chatwoot.gmu.gr`

**Comment by muhsin-k** [comment]
@pranavrajs I agree with you. We need to improve the UX of configure URL screen.

@vfasoulas Could you please try `chatwoot.hmu.gr` instead of `https://chatwoot.hmu.gr`. If you are getting the same error again, please share more details like os version, app version etc.

**Comment by vfasoulas** [comment]
Same error

os:ubuntu 20.04
app version: v1.10.0

In any case it is easy to verify that address https://chatwoot.hmu.gr is online

**Comment by muhsin-k** [comment]
@pwrsurge What about the mobile app version, O.S(Android/iOS)?

**Comment by vfasoulas** [comment]
Android

**Comment by vfasoulas** [comment]
fyi 
I have tested it on iphone and it works as expected

**Comment by pranavrajs** [comment]
@muhsin-k Looks like this is an issue with Android phones only. I was also testing in an iPhone.

**Comment by muhsin-k** [comment]
@vfasoulas Could you please share the **nginx** configuration?

**Comment by vfasoulas** [comment]
server {
         listen 80;
         server_name chatwoot.hmu.gr;
         return 301 https://chatwoot.hmu.gr$request_uri;
}

server {
         listen 443 ssl;
         server_name chatwoot.hmu.gr;

         ssl_certificate /etc/ssl/xxxx.pem;
         ssl_certificate_key /etc/ssl/yyyyy.pem;

         location / {
                 proxy_pass http://localhost:5000/;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "Upgrade";
                 proxy_set_header Host $host;
         }
}

**Comment by pranavrajs** [comment]
@vfasoulas Can you please try this config and see if it helps? https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm#configure-nginx-and-lets-encrypt

**Comment by vfasoulas** [comment]
Finaly the problem is the certificate file, that must contain all certificate chain, not only the certificate for the domain.
I add the additional certificated and now works as excepcted.

Thanks for your help.

**Comment by pranavrajs** [comment]
@muhsin-k Can you please add this information to Linux VM installation guide?
