### ISSUE TITLE
bug: Typing indicators for mobile app

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot-mobile-app#345]
sometimes typing indicators aren't showing up on the web dashboard when I am replying to conversations via mobile app

**Comment by muhsin-k** [comment]
Related to [chatwoot/chatwoot/issues/2015](https://github.com/chatwoot/chatwoot/issues/2015)

**Comment by muhsin-k** [comment]
closing in favor of [chatwoot/chatwoot/issues/2015](https://github.com/chatwoot/chatwoot/issues/2015)
