### ISSUE TITLE
Android app and web app don't push notification to Android 6 notification panel

### ISSUE THREAD

**Issue by par7133** [chatwoot/chatwoot-mobile-app#348]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung Tab SM802C (tablet)
 - OS: Android 6.01
 - Browser: native, derived from Chromium
 - Version: unspecified

**Additional context**

**Comment by muhsin-k** [comment]
Could you please elaborate on this issue? Also please check notification preferences are enabled or not (profile --> settings)

<img width="955" alt="Screenshot 2021-04-01 at 1 19 36 PM" src="https://user-images.githubusercontent.com/12408980/113261310-28a25e00-9284-11eb-93cb-3a3d8352b5b8.png">

**Comment by par7133** [comment]
Yes, push notifications are enabled‎. But no notification are pushed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Muhsin KelothSent: giovedì 1 aprile 2021 09:50To: chatwoot/chatwoot-mobile-appReply To: chatwoot/chatwoot-mobile-appCc: Daniele Bonini; AuthorSubject: Re: [chatwoot/chatwoot-mobile-app] Android app and web app don't push notification to Android 6 notification panel (#348)
Could you please elaborate on this issue? Also please check notification preferences are enabled or not (profile --> settings)


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chatwoot/chatwoot-mobile-app/issues/348#issuecomment-811720132",
"url": "https://github.com/chatwoot/chatwoot-mobile-app/issues/348#issuecomment-811720132",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by muhsin-k** [comment]
@par7133 Are you using chatwoot cloud or self-hosted version?

 The push notification will not work in the official app with the self-hosted instances at the moment([chatwoot/issues/1338](https://github.com/chatwoot/chatwoot/issues/1338)). You will have to build the apps with your own firebase keys.
follow the guidelines described [here](https://rnfirebase.io/#installation) to include the keys while building the react native apps. You will also have to use the same key in your chatwoot server as well.
change environment variables referred [here](https://github.com/chatwoot/chatwoot/blob/29bd05ccfb73ce97b2647f11c24a50c02ef27364/.env.example#L115).

**Comment by par7133** [comment]
I'm using the official instance of chatwoot, the cloud ones.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Muhsin KelothSent: giovedì 1 aprile 2021 11:10To: chatwoot/chatwoot-mobile-appReply To: chatwoot/chatwoot-mobile-appCc: Daniele Bonini; MentionSubject: Re: [chatwoot/chatwoot-mobile-app] Android app and web app don't push notification to Android 6 notification panel (#348)
@par7133 Are you using chatwoot cloud or self-hosted version?
The push notification will not work in the official app with the self-hosted instances at the moment(chatwoot/issues/1338). You will have to build the apps with your own firebase keys.
follow the guidelines described here to include the keys while building the react native apps. You will also have to use the same key in your chatwoot server as well.
change environment variables referred here.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/chatwoot/chatwoot-mobile-app/issues/348#issuecomment-811770657",
"url": "https://github.com/chatwoot/chatwoot-mobile-app/issues/348#issuecomment-811770657",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
