### ISSUE TITLE
Android app running in vertical mode only

### ISSUE THREAD

**Issue by par7133** [chatwoot/chatwoot-mobile-app#349]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**
Android app should run in any context, also when Screen Rotation is on,
and the screen cqn switch to horizontal mode.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.
Tested on Android 6.1

**Comment by muhsin-k** [comment]
@par7133 We don't support landscape mode in mobile app
