### ISSUE TITLE
React Navigation calls not going through 

### ISSUE THREAD

**Issue by surbhitrao** [chatwoot/chatwoot-mobile-app#383]
In the latest stable version of React Navigation i.e 5.x if some data is being fetched from any API the navigations calls won't go through. This causes the chatwoot-mobile-app to lag and as the scene doesn’t change as expected the parts of the app such as opening a conversation from the flatlist feels irresponsive because the navigation call doesn’t go through instantaneously because some data say user avatar image is being fetched while it was tapped. Maybe wix/react-native-navigation can be looked at instead of react-navigation as it's a native implementation.  This is also evident in the Bottom Tabs. On iOS navigation is fast and as expected but on Android, this is a problem even on a decent device.

Some issues created in the official react-navigation repo for reference:

https://github.com/react-navigation/react-navigation/issues/8269

https://github.com/react-navigation/react-navigation/issues/5990

**Comment by muhsin-k** [comment]
@surbhitrao   Thanks for reporting this issue, we will take a look.

**Comment by gpessa** [comment]
I think I have the same

**Comment by surbhitrao** [comment]
@gpessa Hi have you tried the latest code from the develop branch or latest version from the play store? It seems like this issue has been resolved, It might have been related to the actual react native version which was bumped up in the latest version.

**Comment by gpessa** [comment]
May I ask what you have changed?
