### ISSUE TITLE
PDF upload issue

### ISSUE THREAD

**Issue by limeyslimey** [chatwoot/chatwoot-mobile-app#437]
**Describe the bug**

After uploading a pdf inside a chat, the loader keeps on running infinitely even after closing the app and opening the chat in which pdf was uploaded

**To Reproduce**

Upload a pdf inside chatscreen 

**Expected behavior**

The loader should stop once pdf is be uploaded 

**Screenshots**

https://ibb.co/Pcs5nnR

**Environment**

  -  using Chatwoot Cloud (app.chatwoot.com) 
  - Device Name:  Samsung s20
  - OS Version: Android 11
  - Chatwoot App Version: 1.3.16 (downloaded from play store)
  - Chatwoot Server Version: Not sure

**Comment by muhsin-k** [comment]
Apologies for the delay here. We have tested this issue, and PDf upload is working fine. We are closing this issue,for now. Please feel free to reopen this if it still needs to be addressed.
