### ISSUE TITLE
Cannot access notification settings

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#438]
Problem:

I can't access Notification settings from the Android app.  Error screenshot is attached to this mail. 

![Screenshot_20211010-181406_Chatwoot](https://user-images.githubusercontent.com/2246121/136753264-86a664c9-b834-4ca3-b6d6-3e4668fef991.jpg)

**Comment by muhsin-k** [comment]
The issue is already fixed. We are closing this issue, for now. Please feel free to reopen this if it is still an issue.
