### ISSUE TITLE
Mobile App HTML Email display issue

### ISSUE THREAD

**Issue by Stephen-Lobo** [chatwoot/chatwoot-mobile-app#439]
**Describe the bug**

Majority of HTML emails are not displayed well on Mobile App. Maybe there is some CSS rendering issue.

**To Reproduce**

Check any received HTML emails on Mobile App

**Environment**
Docker Ubuntu : Caprover

**Smartphone (please complete the following information):**
Android + IOS

**Comment by Christilut** [comment]
Same here. The message in the Android app just shows an image thumbnail (from the email signature) but no message at all. On web, it shows the full email including signature.
