### ISSUE TITLE
Better conversation resolve UX

### ISSUE THREAD

**Issue by Christilut** [chatwoot/chatwoot-mobile-app#477]
**Is your enhancement request related to a problem? Please describe.**
Resolving a conversation is pretty cumbersome in the app. I have to click the dots in the top, then find the right option.
All options have the same colors so I always have to search.

**Describe the solution you'd like**
A green instant resolve button next to the top right dots. This button should resolve the conversation and go back to the conversation list screen.

**Comment by muhsin-k** [comment]
@Christilut This is a nice addition we will consider it in the upcoming release
