### ISSUE TITLE
Chatwoot Mobile App - Release v2

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#487]
This is a placeholder issue for all release v2.

**Open Questions**

- [ ] Share the usage metrics.
- [ ] Add voice notes functionality for messages
- [ ] Dark theme support
- [ ] Move from  [UI-Kitten](https://github.com/akveo/react-native-ui-kitten) to [Nativebase](https://github.com/GeekyAnts/nativebase)?

**Issues:**

- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/415
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/382
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/421
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/337
- [ ] We are fetching the messages again even if it is available locally.
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/439
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/268
- [ ] Temporary message 
- [ ] app not signing out even after token expires
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/424

**UX issues**

- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/477
- [ ] https://github.com/chatwoot/chatwoot-mobile-app/issues/475

**Comment by Ersonusaini** [comment]
Contact me Install chatwoot on any cloud vps server like aws or gcp or digitalocean etc.
https://wa.me/+919782533298

**Comment by pranavrajs** [comment]
*   Stability Issues
    *   Not reliable enough to use it on low bandwidth connection. Should show an update icon whenever we are fetching data?
    *   Duplicate calls, blocking loaders, app feels slow.
    *   Mobile app should be taking data from local store and fetch the data in background.
*   Message issues
    *   Does not have temporary message available.
    *   Rendering issues with a couple of messages
    *   Issue with rendering emails
*   Performance improvements
    *   Less performant tabs.
*   Missing features
    *   Snooze
    *   Mute
    *   Team Assignment
    *   Label assignment
    *   Rich content editor
    *   Twitter reply features
    *   Read Indicator
    *   Missing user name
    *   Email Headers
*   Feature Improvements
    *   Bloated notifications
    *   Unable to identify the inbox from which the conversation is created

**Comment by muhsin-k** [comment]
https://github.com/chatwoot/chatwoot-mobile-app/issues/506
