### ISSUE TITLE
Invalid installation URL

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot-mobile-app#492]
I try to installed Chatwoot on mobile device (Android and iOS), I'm using self-hosted server,  I've set server url to my domain but when i try to set on my android device  i get response "Invalid Instalation URL". on iOS device it works perfectly

Thanks

**Comment by Ersonusaini** [comment]
Contact me Install chatwoot on any cloud vps server like aws or gcp or digitalocean etc.
https://wa.me/+919782533298

**Comment by muhsin-k** [comment]
@aldhielman Are you sure you tried the same URL for both android and iOS?

**Comment by surbhitrao** [comment]
@aldhielman There's a possibility that on android you must've used auto-fill and that in turn might have added an extra space at the end of the Installation URL. Try after removing the whitespace at the end of the URL.

**Comment by aldhielman** [comment]
> @aldhielman Are you sure you tried the same URL for both android and iOS?

excactly the same, i use `cw.bcperak.net` as my server url

**Comment by muhsin-k** [comment]
@aldhielman I am getting the error message "You got banned permanently from this server" when calling installation URL from android app. Did you add any changes in the app?

![ban](https://user-images.githubusercontent.com/12408980/165544767-eccc1ba9-705a-4db5-8f03-2921ac3a4f69.png)

**Comment by muhsin-k** [comment]
We are closing this issue, for now. Please feel free to reopen this if it still needs to be addressed.

**Comment by lizeshakya** [comment]
Had a similar issue with our self-hosted site as we could not log in to the app (_it was working perfectly on the website_).
Resolved it by fixing the SSL issue.
