### ISSUE TITLE
bug: Filter not work

### ISSUE THREAD

**Issue by drexlma** [chatwoot/chatwoot-mobile-app#498]
https://user-images.githubusercontent.com/7121202/164535160-88538c96-24f4-4fad-8114-c147c49a7372.MOV

**Comment by drexlma** [comment]
Solution: Logout & Login

solved the problem. So will it have anything to do with the session?

**Comment by sojan-official** [comment]
@drexlma  this should be fixed by https://github.com/chatwoot/chatwoot-mobile-app/issues/505
