### ISSUE TITLE
Documentation request for changing font

### ISSUE THREAD

**Issue by limeyslimey** [chatwoot/chatwoot-mobile-app#499]
How can I change the default font by adding a new custom custom font inside assets/font. The documentation provided by UI kitten is not clear. I do understand the part that CustomText will need to have that fontFamily, but that font needs to be 'installed' first, that part is unclear

**Comment by surbhitrao** [comment]
Here's how I was able to change the font globally.

1. Create a folder called "assets", inside it create "fonts" folder and put all your .ttf files inside it. 
2. Edit a file in the root called: `react-native.config.js` :

```
        module.exports = {
                project: {
                        ios: {},
                        android: {}
                },
                assets: ['./assets/fonts']
        };

```

3 - Run this command: `npx react-native link` 

after this for iOS you will run into an issue of duplicate assets, solve it using:
[https://stackoverflow.com/a/62583555/16229711](https://stackoverflow.com/a/62583555/16229711)

4-  Edit mapping.json and replace them with your font, like this
https://gist.github.com/surbhitrao/69634acefdda3417382bcf5c6b5dc1bc

fontFamily name has to be the exact name as the ttf file name. 

There's no change required inside CustomText component.

**Comment by limeyslimey** [comment]
@surbhitrao this works. Closing this issue
