### ISSUE TITLE
Error in notification screen

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#501]
![image](https://user-images.githubusercontent.com/2246121/165264275-8f9314a7-072c-4d10-9e37-8743a6b029e3.png)

I'm getting an error all the time when attempting to use "Notification preferences" in the Android app.

**Comment by muhsin-k** [comment]
@pranavrajs May I know the app version?

**Comment by muhsin-k** [comment]
I am closing this issue, for now since there is no response from customer.
