### ISSUE TITLE
feat: Message Sent status Indicator

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot-mobile-app#509]
**Mockup**
![Simulator Screen Shot - iPhone 8 Plus - 2022-05-05 at 12 47 58](https://user-images.githubusercontent.com/12408980/166878136-cb15d030-5d83-4850-8661-9f791d4bbdf3.png)

[Ref](https://github.com/chatwoot/chatwoot/issues/2587)

**Comment by mariusa** [comment]
The web app shows a message read indicator (2 checkmarks)
Please do the same for Android app, there are no indicators now.

**Comment by muhsin-k** [comment]
Closing in favor of https://github.com/chatwoot/chatwoot-mobile-app/pull/651
