### ISSUE TITLE
License badge is not showing correct info

### ISSUE THREAD

**Issue by yadunandanbhat** [chatwoot/chatwoot-mobile-app#515]
It's showing "not identifiable by github", dont know if it's the badge provider error or something else, instead this below one can be used
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
or Shields.io has autogenerated license badges: https://img.shields.io/github/license/chatwoot/chatwoot-mobile-app

**Comment by yadunandanbhat** [comment]
Can i work on it?

**Comment by muhsin-k** [comment]
@yadunandanbhat Sure. Please go ahead

**Comment by yadunandanbhat** [comment]
Opened a pr. Have a look!
