### ISSUE TITLE
feat: Snooze conversation

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot-mobile-app#517]
- Add option "Snooze conversation" in chat screen context menu-
  - Mark as pending
  - Snooze until (Next reply, Tomorrow, Next week)
- Add snooze status (https://github.com/chatwoot/chatwoot/issues/2985)

**Comment by ChrisvanChip** [comment]
Would be really grateful if this could be implemented in the current app. 

Just a simple "Snooze conversation until reply" button would already boost our productivity :)

**Comment by muhsin-k** [comment]
Fixed via https://github.com/chatwoot/chatwoot-mobile-app/pull/667
