### ISSUE TITLE
Mobile App only accepts domain name for server endpoint

### ISSUE THREAD

**Issue by mh2753** [chatwoot/chatwoot-mobile-app#557]
**Description**
Mobile Apps, both android and iphone, only accept domain names (dont support http:// or https://). This is a bit confusing. Also the error message only returns 'invalid installation url' for all types of problems, so it is not always clear what is missing. 

**To Reproduce**

Install chatwoot app. on the welcome screen enter the self hosted server URL . 

**Expected behavior**

- URL should accept https:// or http:// 
- Error description should be more clear and tell what is wrong with URL

**Comment by muhsin-k** [comment]
I'm sorry for the delay here. We could be able to reproduce this issue from our side, and the team has already started working on it.
