### ISSUE TITLE
[BUG] - Mobile app not notification when have a new conversation (when active Dialogflow chat bot)

### ISSUE THREAD

**Issue by duongvanphung** [chatwoot/chatwoot-mobile-app#562]
When I have not activated the dialogFlow chatbot, all notifications on the mobile app work properly.

But when I enable dialogFlow chatbot no longer receive notifications on mobile app. 
Specifically, the notification has a new conversation

I have tried 2 self-host versions 2.8.1 and 2.9.1. But it not working
So i think bug in mobile app

![bug](https://user-images.githubusercontent.com/49987543/191932599-65c3298c-ab49-4200-8974-a3f9905dc5f2.jpg)

**Comment by muhsin-k** [comment]
Notifications are working fine. We are closing this issue, for now. Please feel free to reopen this if it is still an issue.
