### ISSUE TITLE
Images sent or received are not shown on the Android  Client.

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot-mobile-app#602]
Images sent or received are not shown on the Android Client.

I am unable to see chat images sent or received using the Android Client.

How can we reproduce the issue

* Open a Conversation in the computer browser
* Send or receive a image in the chat
*  Open the same conversation in the Android app and try to see the image - the image will not be shown, as seen below:

**Expected behavior**

Images should be shown the same way they are shown in the browser.

**Screenshots**

![image](https://user-images.githubusercontent.com/86367839/204545092-c337f03b-5800-48c7-91c6-fda2c036a727.png)

![image](https://user-images.githubusercontent.com/86367839/204545225-24b212da-3dea-4923-a694-bbef7ed8b68e.png)

**Environment**

  - Hosted Installation (Docker - latest version)
  - OnePlus 6
  - OS Version: 10.3.11
  - Chatwoot App Version: 1.6.18
  - Chatwoot Server Version: 2.11.0

**Comment by muhsin-k** [comment]
@vagner-dias I just tested by using an android, and it is working. Please test it out with another image. If you can share the image you tried, that would be very helpful to debug.


https://user-images.githubusercontent.com/12408980/204600679-f3349c73-2b34-4ad6-a597-88c8c4928d98.mp4

**Comment by vagner-dias** [comment]
Sure, @muhsin-k 

This is the browser:
![image](https://user-images.githubusercontent.com/86367839/204630332-2ad5740c-313b-43e7-a1d6-465e73fdc886.png)


and this happens in my OnePlus 6:


https://user-images.githubusercontent.com/86367839/204630405-73c86c98-7b95-4437-b1a6-597339058f2b.mp4

**Comment by surbhitrao** [comment]
@vagner-dias 
You can try logging the exact error in the Image component 
`onError=({ nativeEvent: {error} }) => console.log(error)`
I also had a similar problem. In my case, the error pointed out that apparently some formats are not supported in Image component.

I fixed this by replacing Image with [FastImage](https://github.com/DylanVann/react-native-fast-image)

**Comment by muhsin-k** [comment]
@surbhitrao You are right. We have also started to replace all the images with react-native-fast-image.

https://github.com/chatwoot/chatwoot-mobile-app/blob/develop/src/components/UserAvatar/UserAvatar.js#L75

@vagner-dias Could you please try other image types as well?

**Comment by vagner-dias** [comment]
@muhsin-k, in the above example, I was using print-screens.

I have just tested with some other image types (PNG / JPG / GIF). Results below:

Also @surbhitrao - I am using the chatwoot app. How can I enable logging on it ? I could not find any option in the app to enable it.

https://user-images.githubusercontent.com/86367839/204899874-128b8a47-095b-4757-b3fc-6f64ac0fc062.mp4

**Comment by muhsin-k** [comment]
@vagner-dias Did you able to fix this issue?

**Comment by vagner-dias** [comment]
> @vagner-dias Did you able to fix this issue?

Hi @muhsin-k , it is working perfectly now!

Thank you!!!

![Screenshot_20230228-062807](https://user-images.githubusercontent.com/86367839/221810858-603b36b7-eebe-4e44-89de-7cf114dce8f9.jpg)
