### ISSUE TITLE
Apple Carplay and Android Auto notifications

### ISSUE THREAD

**Issue by clanto007** [chatwoot/chatwoot-mobile-app#606]
**Is your feature request related to a problem? Please describe.**
When phone is connected to Android Auto, the smartphone don't receive notifications on Android Auto system and it's shown only on phone screen without audio notifiy. Would be wonderful to receive notification on Android Auto notifications system.

**Describe the solution you'd like**
When receive a notify from App when connected to Android Auto receive notifications on Android Auto Notification System.

**Comment by muhsin-k** [comment]
@clanto007 We dont have any plan to support  carplay notification at the moment. We will look in to once the team have the enough bandwidth. Closing this here, will reopen when we get back to this.
