### ISSUE TITLE
[Build] - Android App

### ISSUE THREAD

**Issue by renat473** [chatwoot/chatwoot-mobile-app#616]
Confirm you’re filing a new issue. [Search issues in Github](https://github.com/chatwoot/chatwoot-mobile-app/issues) and ensure that the issue is not already exist.

**Describe the bug**

`> Configure project :react-native-flipper
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Admin\Desktop\chatwoot-mobile-app\node_modules\react-native-flipper\android\build.gradle' line: 82

* What went wrong:
A problem occurred evaluating project ':react-native-flipper'.
> Could not get unknown property 'FLIPPER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Admin\Desktop\chatwoot-mobile-app\node_modules\react-native-flipper\android\build.gradle' line: 82

* What went wrong:
A problem occurred evaluating project ':react-native-flipper'.
> Could not get unknown property 'FLIPPER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at makeError (C:\Users\Admin\Desktop\chatwoot-mobile-app\node_modules\execa\index.js:174:9)
    at C:\Users\Admin\Desktop\chatwoot-mobile-app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\Admin\Desktop\chatwoot-mobile-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\Admin\Desktop\chatwoot-mobile-app\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
`

**To Reproduce**

When running the command yarn android and returned the error below.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1757167/215097324-b6c075a9-4f42-4d38-a5e4-2a507b3d6b5b.png)

**Observed behavior**

What did you see happen? Please include relevant error messages, screenshots and/or video recordings.

**Environment**

  - Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot.
 
  - Chatwoot Server Version: [develop]

**Additional context**

**Possible fixes**

If you can, link to the line of code that might be responsible for the problem

**Comment by adbasanta** [comment]
@renat473 try to change flipper version to FLIPPER_VERSION=0.99.0 in your android\app\gradle.properties.
I also encountered this problem and this fixed it at least from my side.

**Comment by shivamkb17** [comment]
I am also facing the similar issue, @renat473 did your issue is resolved?

**Comment by coderDancer** [comment]
> @renat473 try to change flipper version to FLIPPER_VERSION=0.177.0 in your android/gradle.properties. I also encountered this problem and this fixed it at least from my side.

It's not ok for me

**Comment by coderDancer** [comment]
![image](https://user-images.githubusercontent.com/22238447/221416279-3c48f37e-a321-43c9-aefd-2d99d6f94623.png)
