### ISSUE TITLE
Fresh install iOS App Invalid Installation URL

### ISSUE THREAD

**Issue by datzent83** [chatwoot/chatwoot-mobile-app#621]
Just did a fresh install of ChatWoot on Ubuntu server. I configured everything to the letter. The website works just fine, but when I put the domain of my self hosted installation I get "Invalid Installation URL" I put the exact same domain I am using on the web browser. I made sure Nginx is properly configured and setup. Not sure what I am missing.

**Comment by datzent83** [comment]
My VM crashed so I had to do another fresh install. 

In the iOS app I am entering chat.qore.tech:3000. I am able to access that URL via any web browser with no problem.

**Comment by datzent83** [comment]
I just reconfigured Nginx and am able to access http://chat.qore.tech. 

I also just tried entering chat.qore.tech in the iOS app and still getting invalid installation url. I even tried with the server's IP address on the local network. Nothing works.

**Comment by muhsin-k** [comment]
@datzent83 Something wrong here. The mobile app checks whether the installation is valid or not using `http://your-chatwoot-url.com/api` endpoint. In your installation, it is not returning anything.

![CleanShot 2023-02-05 at 11 26 28](https://user-images.githubusercontent.com/12408980/216804150-b7a114d8-0ac0-4178-831f-759fe3343e77.png).


The API should return the following payload.

![CleanShot 2023-02-05 at 11 27 40](https://user-images.githubusercontent.com/12408980/216804197-9c845304-f882-4f3b-9d60-2bee47199a6a.png)

**Comment by datzent83** [comment]
Where do I check if the API is properly configured?

**Comment by datzent83** [comment]
I just checked and got this
![Capture](https://user-images.githubusercontent.com/56982404/216804609-97256add-c322-46da-8443-9a0243714b77.JPG)

**Comment by muhsin-k** [comment]
![CleanShot 2023-02-05 at 13 06 13](https://user-images.githubusercontent.com/12408980/216807297-ddcdbe6d-efe3-4bdd-8b31-41517eb81958.png)

**Comment by datzent83** [comment]
I tried all the logins. Nothing worked.

**Comment by muhsin-k** [comment]
@datzent83 Could you please schedule a call at https://calendly.com/muhsin-keloth. I will definitely look into this issue.

**Comment by NaturalGao** [comment]
@muhsin-k Please let me know how is the solution, I also encountered this problem

**Comment by muhsin-k** [comment]
@datzent83 @NaturalGao 
Please check whether you are set up `SSL` or not. We don't support unsecured domains at the moment.
