### ISSUE TITLE
Getting build error ( BUNDLE  ./index.js)

### ISSUE THREAD

**Issue by manojdhimann** [chatwoot/chatwoot-mobile-app#634]
**Describe the bug**

When I am running yarn android cmd, I am getting this error after the APK SUCCESSFUL build.

![Screenshot 2023-02-24 at 2 02 46 PM](https://user-images.githubusercontent.com/32815842/221130694-b0093c03-b2ad-4576-8ad6-2e7ac891c5b8.png)

**Comment by muhsin-k** [comment]
@manojdhimann This isssue will fix via https://github.com/chatwoot/chatwoot-mobile-app/pull/620

**Comment by manojdhimann** [comment]
Thanks :)
