### ISSUE TITLE
Fastlane Issue | Android build

### ISSUE THREAD

**Issue by manojdhimann** [chatwoot/chatwoot-mobile-app#635]
CMD: fastlane android test

Working DIR: /Users/manojdhiman/Office/new/chatwoot-mobile-app/android/fastlane

BRANCH: develop
commit: 534897a901675ce0cfa4246211fd3dead1238da6

> Task :app:bundleReleaseJsAndAssets_SentryCollectModules_com.chatwoot.app@1.7.46+5116003_5116003
Sentry Logger [info]: Reading source map from /Users/manojdhiman/Office/new/chatwoot-mobile-app/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
Sentry Logger [info]: Saving modules to /Users/manojdhiman/Office/new/chatwoot-mobile-app/android/app/src/main/assets/modules.json
Sentry Logger [info]: Resolving modules from paths /Users/manojdhiman/Office/new/chatwoot-mobile-app/android/app/src/main/assets/modules.json
Sentry Logger [info]: Modules collected and saved to: /Users/manojdhiman/Office/new/chatwoot-mobile-app/android/app/src/main/assets/modules.json
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload_com.chatwoot.app@1.7.46+5116003_5116003'.
> Process 'command '/Users/manojdhiman/Office/new/chatwoot-mobile-app/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload_com.chatwoot.app@1.7.46+5116001_5116001'.
> Process 'command '/Users/manojdhiman/Office/new/chatwoot-mobile-app/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by manojdhimann** [comment]
@fayazara Could you please assign someone to check this issue?

**Comment by fayazara** [comment]
Cc @muhsin-k

**Comment by muhsin-k** [comment]
@manojdhimann Did you setup google service account. Please see this [guide](https://docs.fastlane.tools/actions/supply/#setup) for more details

**Comment by manojdhimann** [comment]
Sure, but I have only one question: What does "custom release" mean when we have to manually enter the installation URL in the app at the beginning of the installation? Because I have defined the URL of my self-hosted server in the AndroidManifest.xml file according to the documentation. So should I have the option to enter the installation URL at the beginning, or am I doing something wrong?

I'm sorry if I'm asking a bad question because I have absolutely no idea about app development. I am just a DevOps engineer.

![IMG_8895](https://user-images.githubusercontent.com/32815842/221783639-ec7fd2ce-b732-49ef-89a4-2c5f188aaf73.jpg)

**Comment by muhsin-k** [comment]
@manojdhimann You need to update this value [here](https://github.com/chatwoot/chatwoot-mobile-app/blob/develop/src/screens/ConfigureURLScreen/ConfigureURLScreen.js#L55).
