### ISSUE TITLE
The push new message is not displayed iOS

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot-mobile-app#655]
Confirm you’re filing a new issue. [Search issues in Github](https://github.com/chatwoot/chatwoot-mobile-app/issues) and ensure that the issue is not already exist.

**Describe the bug**

The message is not displayed in the mobile application when you click on push notifications, you have to wait 3-4 minutes or manually restart the application.

**To Reproduce**

1. The chatwoot application on the smartphone is launched and minimized
2. I go to the website and write to the chatwoot online chat widget
3. On the agent's smartphone, a push notification is displayed with the message "Hello" in the conversation ID - 229
4. I open push, the chatwoot application opens
5. There is no "Hello" message in conversation ID - 229
6. I send another message from the online chat "Hello2" and it was displayed in the conversation with the agent
7. In the mobile application, I open the dialog again - to get an update and then the message "Hello" appears

**Expected behavior**

When I click on push with a new message, a conversation opens and this message is displayed in the history feed

**Screenshots**

https://drive.google.com/file/d/1GhDHxvIanV0CwVEg9tqF1gqLhkXc0j_U/view?usp=share_link

**Observed behavior**

What did you see happen? Please include relevant error messages, screenshots and/or video recordings.

**Environment**

  - Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot.
  - Device Name:  [e.g. iPhone13 pro max]
  - OS Version: [e.g. iOS16.3.1]
  - Chatwoot App Version: [e.g. 1.8.0]
  - Chatwoot Server Version: [e.g. 2.14.0]

**Comment by muhsin-k** [comment]
@aerostovtsev Can you please update to the v1.8.4 and check issue is fixed or not? We have already added a fix for updating the conversation on the awake event.

**Comment by aerostovtsev** [comment]
Thanks you! Issue resolved
