### ISSUE TITLE
Not able to close conversation in whatsapp leatest chatwoot app release 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot-mobile-app#659]
I update the chatwoot app from play store then there's no more option to close conversation or add label or assign agent

![Screenshot_20230322-021214_Chatwoot](https://user-images.githubusercontent.com/20530550/226762789-087f7f54-3556-4b3b-8da8-edad3d774a57.jpg)

**Comment by muhsin-k** [comment]
We have tested this issue from our side in android, and it is working fine for me. Can you check a couple of other WhatsApp conversations as well?

![photo_2023-03-23 16 52 55](https://user-images.githubusercontent.com/12408980/227189259-0aa35e3f-6816-45a4-8c3b-c52e24806ee1.jpeg)
