### ISSUE TITLE
App translation

### ISSUE THREAD

**Issue by arthurbarret0** [chatwoot/chatwoot-mobile-app#676]
In the Brazilian Portuguese translation, "SETTINGS" is translated as "Confirgurações", instead of "Configurações". In English, it would be equivalent to "Settnigs".

![config](https://user-images.githubusercontent.com/54091091/230123279-81d3e51f-a5f8-4e88-8850-8b85219f5c4b.jpg)

**Comment by muhsin-k** [comment]
We use [Crowdin](https://crowdin.com/) to manage the translations. Please refer to the [guide](https://www.chatwoot.com/docs/contributing-guide/translation-guidelines/) for details.
