### ISSUE TITLE
Error: TypeError - Undefined is not an object

### ISSUE THREAD

**Issue by dhwaj1902** [chatwoot/chatwoot-mobile-app#683]
Getting error on chatwoot app. Attached a image for the error.

Working correctly on website.

<img src="https://user-images.githubusercontent.com/57860123/235110705-49aa9da0-05a0-42b1-93bf-f993023d1fb7.png" height="500px" />

**Environment**
Self Hosted Using Linux

**Comment by muhsin-k** [comment]
@dhwaj1902 Are you getting this error when you open a particular conversation, or is it happening constantly? If it happens for one conversation, can you also share browser console logs?

**Comment by dhwaj1902** [comment]
I actually don't know, whether it was for one conversation or anything else, but everything working fine in browser. I am only using whatsapp channel for communication.

**Comment by muhsin-k** [comment]
@dhwaj1902 As per our investigation, the problem is occurring only in self-hosted installations. Could you grant me access as an agent in your account so that I can further investigate the problem? Thank you. My email id is [muhsin@chatwoot.com](mailto:muhsin@chatwoot.com)

**Comment by muhsin-k** [comment]
We have fixed this issue in `v1.9.8`. I am closing this issue for now. Please feel free to reopen this if it is still an issue.
