### ISSUE TITLE
incomplete translation for german language

### ISSUE THREAD

**Issue by sadden3194** [chatwoot/chatwoot-mobile-app#687]
![grafik](https://user-images.githubusercontent.com/17011498/236641886-99f879fa-1f29-4293-b5e2-f2fb8e42d367.png)

Mine = Meine
Open = Offene

![IMG_2475](https://user-images.githubusercontent.com/17011498/236641951-78fa0d0d-7c8e-4840-8c8d-e4a7725455d0.PNG)

Mine = Meine
Unassigned = Nicht zugewiesen
All = Alle

![IMG_2476](https://user-images.githubusercontent.com/17011498/236641987-870e72b4-5c24-4a7b-be8e-2a11453c6ee4.PNG)

Open = Offene
Resolved = Gelöst
Pending = Ausstehend
Snoozed  = Geparkt
All = Alle

![IMG_2477](https://user-images.githubusercontent.com/17011498/236642255-44b1b6d6-babb-4a3b-9ba2-fb1926addd1e.PNG)

Preferences = Einstellungen
Switch Account = Account wechseln
Notification Preferences = Benachrichtigungseinstellungen
Change Language = Sprache ändern
Read Docs = Dokumentation lesen
Chat with us = Chatte mit uns

**Comment by muhsin-k** [comment]
We use [Crowdin](https://crowdin.com/) to manage the translations. Please refer to the [guide](https://www.chatwoot.com/docs/contributing-guide/translation-guidelines/ ) for details.

**Comment by Ghost108** [comment]
I updated many strings for german language via crowdin.

**Comment by Ghost108** [comment]
Hi all,

I would like to reactive this post, because the translations arent correctly, yet. (no changes until today).
As I can see, the strings are translatet (https://translate.chatwoot.com/chatwoot-mobile-app) but are still not displayed correctly in app (same words like in my first post)

**Comment by Ghost108** [comment]
Thanks! :)

**Comment by muhsin-k** [comment]
Closing this issue since this is already completed.
