### ISSUE TITLE
Duplicate of assets folder

### ISSUE THREAD

**Issue by wadekar9** [chatwoot/chatwoot-mobile-app#726]
**Is your enhancement request related to a problem? Please describe.**
Yes, It's confusing for new contributor to check which assets folder in used.

**Describe the solution you'd like**
- Change location/route for fonts from "assets/.." to "src/assets/fonts/...".
- Also changed path in react-native.config.js file.

<img width="195" alt="Screenshot 2023-08-06 at 10 35 24 PM" src="https://github.com/chatwoot/chatwoot-mobile-app/assets/107600846/232fb078-5ad0-4be9-9c25-9bbbe9172850">
<br>
<img width="405" alt="Screenshot 2023-08-06 at 10 36 20 PM" src="https://github.com/chatwoot/chatwoot-mobile-app/assets/107600846/eb3158c7-bce2-49fc-b55e-2204383e02af">

**Comment by zaronwald** [comment]
I can do this right now really quickly

**Comment by zaronwald** [comment]
Just need PR approved

**Comment by zaronwald** [comment]
@muhsin-k @sojan-official can we merge the pr for this?
