### ISSUE TITLE
Cannot read old conversations when there is no internet connection

### ISSUE THREAD

**Issue by dlc-letelier** [chatwoot/chatwoot-mobile-app#765]
**Describe the bug**

Because of the update when the app is open, when there is no connection to the Chatwoot server, the app keep refreshing, so I cannot check the old conversation. I have a lot of agents that works outside, but sometimes they cannot check the old messages, because there is no internet connection.

**To Reproduce**

* Open Chatwoot app
* Turn on the airplane mode
* Try to check for messages
Also happens when the app is open without internet conection

**Expected behavior**

Only updates when the connection with the server is reach, and not block the possibility to read the old messages.

**Screenshots**

![IMG_1101](https://github.com/chatwoot/chatwoot-mobile-app/assets/60855725/99b590d7-0978-44a4-b99e-37baa0e8b0b2)

**Environment**

  - iOS 17
  - Version 1.10.28

**Comment by pranavrajs** [comment]
@dtc-letleier We don't have offline capabilities at the moment. This is not supported. You can view the conversations when there is an active network connection,
