### ISSUE TITLE
Unable to load env using react native config while release 

### ISSUE THREAD

**Issue by avinash-marsdevs** [chatwoot/chatwoot-mobile-app#777]
**Describe the bug**

When running yarn android:release in a React Native project, the environment configurations do not load. However, the configurations load as expected when running yarn start. This issue occurs in a setup with a self-hosted domain URL of Chatwoot and a modified namespace.

**To Reproduce**

**Steps to reproduce the behavior:**

- Set up a self-hosted Chatwoot environment with a custom domain URL and modified namespace.
- Configure React Native project to use environment-specific settings.
- Run yarn start to confirm that the environment settings load correctly.
- Run yarn android:release and observe that the environment settings are not loaded.

**Expected behavior**
The environment configurations should load consistently across both development (yarn start) and production builds (yarn android:release).

**Observed behavior**

The configurations that load correctly during yarn start are not loaded when executing yarn android:release. This results in default or empty configuration values being used, impacting the functionality depending on these configurations.

**Environment**

Chatwoot Installation: Self-hosted

**Additional context**

The issue seems related to the way environment variables are managed and loaded in the release build process. The react-native-config library is used for managing environment variables and might be misconfigured for production builds.

[Attached changes diff](https://github.com/chatwoot/chatwoot-mobile-app/files/15152425/changes.txt)

**Comment by avinash-marsdevs** [comment]
https://github.com/lugg/react-native-config/issues/770

Might be a problem with react-native-config itself I guess

**Comment by avinash-marsdevs** [comment]
`
def enableProguardInReleaseBuilds = false
`
`
minifyEnabled enableProguardInReleaseBuilds
`

this change did the magic. but if I need to enable proguard, I wonder what will be the resolution!

**Comment by muhsin-k** [comment]
We are able to load all the variables from our testing. Closing this issue, for now. Please feel free to reopen this if it is still an issue.
