### ISSUE TITLE
Push Notifications Not Working in Custom Mobile App with Self-Hosted Server

### ISSUE THREAD

**Issue by avinash-marsdevs** [chatwoot/chatwoot-mobile-app#778]
**Describe the Bug**
Push notifications are not working in our custom Chatwoot mobile app connected to a self-hosted Chatwoot server. Despite updating the `ANDROID_BUNDLE_ID`, setting the `ENABLE_PUSH_RELAY_SERVER` environment variable to true/false, and updating the `FCM_SERVER_KEY` and Google services JSON for Android, push notifications fail to be received.

**To Reproduce**
1. Update the server with the new `FCM_SERVER_KEY`, `ANDROID_BUNDLE_ID`, and set `ENABLE_PUSH_RELAY_SERVER` to true.
2. Update the mobile app with the new Google services JSON.
3. Send a message to trigger a push notification.
4. Notice that the notification does not appear on the device.

**Expected Behavior**
Expected that the push notifications would be received on the device whenever a new message is sent or received in the app.

**Observed Behavior**
No push notifications are received on the device. No relevant error messages appear in the server logs, indicating a silent failure or misconfiguration.

**Environment**
- Chatwoot Self-Hosted Server Version: 3.4.0
- Custom Chatwoot Mobile App Version: 1.10.38
- OS Version: Android 14

**Additional Context**
All required configurations and environmental variables have been updated as per the documentation.

**Comment by gicellamare** [comment]
Same problem here

**Comment by fabioginzel** [comment]
+1

**Comment by avinash-marsdevs** [comment]
its started working fine after I did `ENABLE_PUSH_RELAY_SERVER = false` 

then its started working fine. but now FCM was deprecated so need to upgrade 3.10.0. will have to check again anyhow

**Comment by laianeramos** [comment]
Hi! In version 3.10 and mobile app 1.0.41, do I just need to set ENABLE_PUSH_RELAY_SERVER to true? Or do I need do add FCM_SERVER_KEY and ANDROID_BUNDLE_ID too? Where can I get this ids/keys? 
thank you

> If you're using the official mobile app, push notifications should function without problems. Be sure that the environment variable ENABLE_PUSH_RELAY_SERVER is set to true. In the latest version [3.10](https://firebase.google.com/docs/cloud-messaging/migrate-v1), we've included FCM HTTP v1 updates. Additionally please upgrade the mobile app to version [1.0.41](https://github.com/chatwoot/chatwoot-mobile-app/releases/tag/v1.0.41).

**Comment by muhsin-k** [comment]
@laianeramos FCM changes are only necessary for users who have a **custom-branded** mobile app. A detailed guide for this will be created soon.

**Comment by Liliadetassia** [comment]
so funciona com app personalizado isso?

**Comment by laianeramos** [comment]
> @laianeramos FCM changes are only necessary for users who have a **custom-branded** mobile app. A detailed guide for this will be created soon.

@muhsin-k  I'm using the official mobile app, the environment variable ENABLE_PUSH_RELAY_SERVER is set to true, i'm using the latest versions of chatwoot web and mobile app, but push notifications are not working. I'm waiting for the guide to see if i'm doing anything wrong

**Comment by muhsin-k** [comment]
@laianeramos https://www.chatwoot.com/docs/contributing-guide/mobile-app/custom-release-guide#setup-firebase-for-push-notification

Please check whether you have enabled the notification preferences in profile settings. 
![CleanShot 2024-07-10 at 08 40 24@2x](https://github.com/chatwoot/chatwoot-mobile-app/assets/12408980/244974a5-e813-40b7-a4be-a184d8e07d8f)

**Comment by muhsin-k** [comment]
Closing this issue, for now. Please feel free to reopen this if it is still an issue.

**Comment by mayank-gc** [comment]
Hey @muhsin-k 
We are using self-hosted chatwoot (v3.3.2) with an official android mobile app (v1.10.44)
We have set **ENABLE_PUSH_RELAY_SERVER** to true

After debugging we encountered these errors

1st error - 
{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Invalid JSON payload received. Unknown name \\\"sound\\\" at 'message.notification': Cannot find field.\\nInvalid JSON payload received. Unknown name \\\"collapse_key\\\" at 'message': Cannot find field.\",\n    \"status\": \"INVALID_ARGUMENT\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.BadRequest\",\n        \"fieldViolations\": [\n          {\n            \"field\": \"message.notification\",\n            \"description\": \"Invalid JSON payload received. Unknown name \\\"sound\\\" at 'message.notification': Cannot find field.\"\n          },\n          {\n            \"field\": \"message\",\n            \"description\": \"Invalid JSON payload received. Unknown name \\\"collapse_key\\\" at 'message': Cannot find field.\"\n          }\n        ]\n      }\n    ]\n  }\n}\n

After removing **sound**, **collapse_key** parameters from https://hub.2.chatwoot.com/send_push API.

We got another error - 
{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Recipient of the message is not set.\",\n    \"status\": \"INVALID_ARGUMENT\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.BadRequest\",\n        \"fieldViolations\": [\n          {\n            \"field\": \"message\",\n            \"description\": \"Recipient of the message is not set.\"\n          }\n        ]\n      },\n      {\n        \"@type\": \"type.googleapis.com/google.firebase.fcm.v1.FcmError\",\n        \"errorCode\": \"INVALID_ARGUMENT\"\n      }\n    ]\n  }\n}\n

**Comment by mastermailgeral** [comment]
Same problem here. No notifications using the oficial mobile app with self host installation.

**Comment by muhsin-k** [comment]
@mayank-gc It seems you're using an old version of Chatwoot. You need to upgrade to Chatwoot version [3.10.0](https://github.com/chatwoot/chatwoot/releases/tag/v3.10.0). Push notifications won't work for earlier versions due to Firebase's API level changes.

**Comment by mastermailgeral** [comment]
@muhsin-k I have the 3.12.0 version and the problem persists.

**Comment by muhsin-k** [comment]
> It seems you're using an old version of Chatwoot. You need to upgrade to Chatwoot version [3.10.0](https://github.com/chatwoot/chatwoot/releases/tag/v3.10.0). Push notifications won't work for earlier versions due to Firebase's API level changes.
@mayank-gc Did you make the changes?

**Comment by muhsin-k** [comment]
@mastermailgeral Please check you have followed this [guide](https://chatwoot.help/hc/handbook/articles/1687935909-push-notification) properly or not.

**Comment by mastermailgeral** [comment]
@muhsin-k Yes, i follow the guide and i declare the variable ENABLE_PUSH_RELAY_SERVER=true, but only when i open the oficial mobile app, the app refresh and i see the new messages. I have installed Chatwood on docker.

**Comment by notridan** [comment]
I have the same problem, chatwoot self hosted and official app, variable set to true and push notifications don't work, has anyone solved it?

**Comment by natanaelece** [comment]
I have the same problem, chatwoot self hosted and official app, variable set to true and push notifications don't work, has anyone solved it?

**Comment by antoinesco** [comment]
I have exactly the same issue.
Selfhosted chatwoot + ENABLE_PUSH_RELAY_SERVER=true + official iOS app and notifications are not working + new messages are visible only when updating the app window.

**Comment by sanjayws** [comment]
> [@laianeramos](https://github.com/laianeramos) https://www.chatwoot.com/docs/contributing-guide/mobile-app/custom-release-guide#setup-firebase-for-push-notification
> 
> Please check whether you have enabled the notification preferences in profile settings. ![CleanShot 2024-07-10 at 08 40 24@2x](https://github.com/chatwoot/chatwoot-mobile-app/assets/12408980/244974a5-e813-40b7-a4be-a184d8e07d8f)

Hi @muhsin-k , im trying out to build a custom branded app, but this link above is not working and goes to the generic page(s)., basically needing some help with push, the app gets built properly and is now tested in google play. All works fine, including in app push, but not push notifications when app closed (killed).

Thanks for looking at this. 
Sanjay

**Comment by horror** [comment]
same problem Selfhosted chatwoot + ENABLE_PUSH_RELAY_SERVER=true + official android app. Not receive pushes

**Comment by hitbruno** [comment]
Hi everyone, the same problem here. Selfhosted, official IOS app.
