### ISSUE TITLE
Have a larger default font size

### ISSUE THREAD

**Issue by teolemon** [chatwoot/chatwoot-mobile-app#788]
### What
- On a Pixel 6 with default settings, it's hard to read incoming emails (see Screenshot)

### Proposed solution 
- increase font size at the expense of density 
- make it possible for users to choose their font size 

### Screenshot 
![Screenshot_20240613-115542.png](https://github.com/chatwoot/chatwoot-mobile-app/assets/1689815/13db3350-3d36-495d-8683-076d758ef060)

**Comment by muhsin-k** [comment]
We have been working on an improved version of the mobile app with all the accessibility fixes. Closing this for now.
