### ISSUE TITLE
chore: App must target Android 14 (API level 34) or higher

### ISSUE THREAD

**Issue by KKshitiz** [chatwoot/chatwoot-mobile-app#795]
**Is your enhancement request related to a problem? Please describe.**
Got this violation from Google Play a couple days back. Will need to update before `Aug 31, 2024` to be able to release further updates to the app

**Describe the solution you'd like**
Upgrade the target SDK version to Android 14 (API level 34) or higher to be compliant with Google Play's policies going forward.

**Screenshot for the issue**
![Screenshot from 2024-07-10 15-55-53](https://github.com/chatwoot/chatwoot-mobile-app/assets/37079141/cff48f2e-56f0-4a11-bf5d-bdb86bd1dcaa)

**Additional context**
[Here](https://developer.android.com/google/play/requirements/target-sdk) are the play store guidelines for the same.

**Comment by shivamkb17** [comment]
There is already it is fixed in latest release.

**Comment by muhsin-k** [comment]
@KKshitiz We will work on this soon. Additionally, we need to update the React Native version to upgrade the API level.

**Comment by muhsin-k** [comment]
Fixed via https://github.com/chatwoot/chatwoot-mobile-app/pull/797
